Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

ANS_1:_
Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list, whereas array_list is a NumPy array.

In [1]:
#CODE:-

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

ANS_2:-

In [2]:
#CODE:-

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

ANS_3:-

Yes, there will be a difference in the data type of the elements present in list_ and array_list after setting dtype=int for array_list. The elements in list_ will remain strings, while the elements in array_list will be converted to integers.

In [3]:
#CODE:-

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Data types of elements in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

print("\nData types of elements in num_array:")
for element in num_array.flatten():
    print(type(element))


Data types of elements in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in num_array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

ANS_4:-

In [4]:
#CODE:-

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

shape = num_array.shape
print(f"Shape of num_array: {shape}")

size = num_array.size
print(f"Size of num_array: {size}")


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

ANS_5:-

In [5]:
#CODE:-

import numpy as np

zero_matrix = np.zeros((3, 3))

print("3x3 matrix of zeros:")
print(zero_matrix)


3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

ANS_6:

In [6]:
#CODE:-

import numpy as np
identity_matrix = np.eye(5)

print("5x5 identity matrix:")
print(identity_matrix)


5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
